type AutoGenerated []struct {
	Players []struct {
		Q             int  `json:"q"`
		R             int  `json:"r"`
		S             int  `json:"s"`
		Points        int  `json:"points"`
		Shield        bool `json:"shield"`
		Alive         bool `json:"alive"`
		Missiles      int  `json:"missiles"`
		MissilesFired []struct{
		    Q int `json:"q"`
		    R int `json:"r"`
		    S int `json:"s"`
		} `json:"missiles_fired"`
	} `json:"players"`
	Map struct {
		Moveleft         int   `json:"moveleft"`
		Radius           int   `json:"radius"`
		TreasureRemaining bool `json:"treasure_remaining"`
		Cells            []struct {
			Q     int    `json:"q"`
			R     int    `json:"r"`
			S     int    `json:"s"`
			Value string `json:"value"`
		} `json:"cells"`
	} `json:"map"`
}
